/user/delete/{id}:
  delete:
    tags:
      - User
    summary: Deletes a specific user.
    security:
      - BearerAuth: []
    description: Deletes a specific user based on the provided ID.
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: ID
    responses:
      200:
        description: User successfully deleted
        content:
          application/json:
            example:
                message: "User deleted successfully"
      400:
        description: User not found!
